server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: krishna123
    url: jdbc:mysql://localhost:3306/contact
    username: root
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      platform: =mysql


app: 
  messages: 
    contactSavedSucc: Contact Saved
    contactsaveFail: Failed to save contact
    contactDelSucc: Contact Deleted
    contactDelFail: Failed to delete contact 